# 3차시 ― 수학 기초 · 벡터와 행렬

> 앞 노트북에서 파이썬의 변수·자료형·리스트를 익혔습니다. 이번 노트북에서는 AI 계산의 **기본 재료**인 **벡터**와 **행렬**을 다룹니다. 4차시(머신러닝 만들기)와 5차시(딥러닝·RAG 챗봇)에서 쓰는 임베딩·유사도 계산이 모두 여기서 출발합니다.
>
> 손으로 식을 푸는 대신 **NumPy** 라는 도구로 계산합니다. Colab에는 이미 설치되어 있어 바로 쓸 수 있습니다.
>
> **실행 방법**: 코드 셀을 클릭하고 `Shift + Enter`. 위에서 아래로 순서대로 실행하세요. 앞 셀에서 만든 변수를 뒤 셀에서 사용합니다.

**다루는 내용**
1. NumPy 도입 — 왜 리스트 대신 배열인가
2. 벡터 만들기와 산술 — 덧셈·뺄셈·스칼라곱
3. 내적 — 대응 원소를 곱해 더하기
4. 노름 — 벡터의 길이
5. 코사인 유사도 — 방향이 비슷한 정도
6. 행렬 — shape·전치·행렬곱
7. 이미지 = 숫자 행렬
8. (선택) 임베딩으로 문장 유사도 — 4·5차시 예고
9. 마무리

> 📌 **✍️ 표시가 붙은 "연습문제"는 직접 입력하는 칸입니다.** 강사와 함께 한 줄씩 따라 입력해 봅니다.

## 1. NumPy 도입 — 왜 리스트 대신 배열인가
**NumPy**(넘파이)는 숫자 묶음을 빠르고 간단하게 계산해 주는 파이썬 도구입니다. 관례적으로 `np` 라는 짧은 이름으로 불러옵니다.

파이썬 기본 **리스트**로 숫자끼리 더하면 우리가 기대하는 '같은 자리끼리 더하기'가 되지 않습니다. NumPy 배열(`np.array`)을 쓰면 됩니다.

In [ ]:
import numpy as np   # numpy 를 np 라는 이름으로 불러오기 (관례)

print(np.__version__)   # 설치된 버전 (예: 1.26.4) — Colab엔 이미 있음

### 1-1) 리스트 vs np.array
같은 `+` 기호인데 결과가 다릅니다. 리스트는 **이어붙이고**, 배열은 **같은 자리끼리 더합니다**.

In [ ]:
py_list = [1, 2, 3] + [4, 5, 6]   # 리스트의 + 는 이어붙이기
print('리스트:', py_list)          # 리스트: [1, 2, 3, 4, 5, 6]

np_arr = np.array([1, 2, 3]) + np.array([4, 5, 6])   # 배열의 + 는 자리끼리 더하기
print('배열  :', np_arr)           # 배열  : [5 7 9]

## 2. 벡터 만들기와 산술
**벡터**는 여러 숫자를 한 줄로 나열한 묶음입니다. 예를 들어 `[3, 4]` 는 숫자 2개로 이루어진 2차원 벡터입니다. `np.array()` 에 리스트를 넣어 만들고, `.shape` 로 원소 개수(차원)를 확인합니다.

In [ ]:
v = np.array([3, 4])   # 2차원 벡터
print('벡터 v:', v)     # 벡터 v: [3 4]
print('shape :', v.shape)   # shape : (2,)   ← 원소 2개
print('1번 원소:', v[1])     # 1번 원소: 4    ← 리스트처럼 0번부터 인덱싱

### 2-1) 덧셈·뺄셈 — 같은 자리끼리
두 벡터를 더하거나 빼면 같은 위치의 숫자끼리 계산됩니다. (그래서 길이가 같아야 합니다.)

In [ ]:
v1 = np.array([1, 2])
v2 = np.array([3, 4])
print('v1 + v2 =', v1 + v2)   # v1 + v2 = [4 6]
print('v1 - v2 =', v1 - v2)   # v1 - v2 = [-2 -2]

### 2-2) 스칼라곱 — 숫자 하나를 전체에 곱하기
벡터에 숫자(스칼라) 하나를 곱하면 모든 원소에 똑같이 곱해집니다. 벡터의 **방향은 그대로**, **길이만** 늘거나 줄어듭니다.

In [ ]:
v = np.array([1, 2, 3])
print('2 * v =', 2 * v)     # 2 * v = [2 4 6]   (2배로 늘어남)
print('0.5 * v =', 0.5 * v) # 0.5 * v = [0.5 1.  1.5]   (절반으로 줄어듦)

> ## ✍️ 연습문제 1 · 함께 입력해 봐요

- 벡터 `a = np.array([2, 5, 1])`, `b = np.array([4, 0, 3])` 을 만드세요.
- `a + b`, `a - b`, 그리고 `a` 의 3배(`3 * a`)를 각각 출력하세요.

In [ ]:
# ✍️ 여기에 직접 작성하세요


## 3. 내적 — 대응 원소를 곱해 더하기
**내적(dot product)** 은 같은 자리의 숫자끼리 곱한 뒤 **모두 더한** 값입니다. 결과는 벡터가 아니라 **하나의 수(스칼라)** 입니다.

예: `[1, 2, 3] · [4, 5, 6] = 1×4 + 2×5 + 3×6 = 4 + 10 + 18 = 32`

NumPy에서는 `@` 연산자(또는 `np.dot`)로 한 번에 구합니다.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('a @ b   =', a @ b)        # a @ b   = 32
print('np.dot  =', np.dot(a, b)) # np.dot  = 32   (같은 결과)

# 직접 풀어 쓰면 이런 계산입니다
print('펼쳐서 :', 1*4 + 2*5 + 3*6)   # 펼쳐서 : 32

> ## ✍️ 연습문제 2 · 함께 입력해 봐요

- 벡터 `x = np.array([2, 3])`, `y = np.array([4, 1])` 을 만드세요.
- `x` 와 `y` 의 내적을 `@` 로 구해 출력하세요. (손으로 계산하면 2×4 + 3×1 = 11 입니다.)

In [ ]:
# ✍️ 여기에 직접 작성하세요


## 4. 노름 — 벡터의 길이
**노름(norm)** 은 벡터의 길이, 즉 원점에서 끝점까지의 거리입니다. 가장 많이 쓰는 **L2 노름** 은 피타고라스 정리로 구합니다.

예: 벡터 `[3, 4]` 의 길이는 직각삼각형의 빗변과 같아서 `√(3² + 4²) = √25 = 5` 입니다.

`np.linalg.norm()` 으로 계산합니다.

In [ ]:
v = np.array([3, 4])
print('L2 노름:', np.linalg.norm(v))   # L2 노름: 5.0

# 직접 풀어 쓰면: 제곱해서 더하고 제곱근
print('펼쳐서 :', (3**2 + 4**2) ** 0.5)   # 펼쳐서 : 5.0

### 4-1) 거리를 재는 다른 방법 (참고)
- **L1 노름**: 원소 절댓값을 모두 더한 값 (`norm(v, 1)`)
- **L2 노름**: 피타고라스 거리 — 기본값 (`norm(v)`)

상황에 따라 다른 거리를 쓰지만, 우리가 앞으로 주로 쓰는 것은 L2 입니다.

In [ ]:
v = np.array([3, 4])
print('L1 노름:', np.linalg.norm(v, 1))   # L1 노름: 7.0   (|3| + |4|)
print('L2 노름:', np.linalg.norm(v, 2))   # L2 노름: 5.0   (기본값)

> ## ✍️ 연습문제 3 · 함께 입력해 봐요

- 벡터 `w = np.array([6, 8])` 을 만드세요.
- `w` 의 L2 노름(길이)을 `np.linalg.norm` 으로 구해 출력하세요. (정답은 10.0 입니다.)

In [ ]:
# ✍️ 여기에 직접 작성하세요


## 5. 코사인 유사도 — 방향이 비슷한 정도
두 벡터가 **얼마나 닮았는지** 를 잴 때, 길이는 빼고 **방향(사이각)** 만 보는 방법이 **코사인 유사도** 입니다.

- 방향이 **같으면** 1 에 가깝고,
- **수직(직각)** 이면 0,
- **반대** 방향이면 음수가 됩니다.

식은 `내적 ÷ (두 벡터의 길이를 곱한 값)` 입니다. 즉 내적을 길이로 나눠 **방향 정보만** 남긴 것입니다.

$$\cos\theta = \frac{a \cdot b}{\lVert a \rVert \, \lVert b \rVert}$$

In [ ]:
def cosine_similarity(a, b):
    # 내적을 두 벡터 길이의 곱으로 나눈다
    return (a @ b) / (np.linalg.norm(a) * np.linalg.norm(b))

a = np.array([1, 0])
b = np.array([1, 0])   # a 와 완전히 같은 방향
print('같은 방향 :', cosine_similarity(a, b))   # 같은 방향 : 1.0

### 5-1) 방향에 따라 값이 어떻게 변할까
기준 벡터 `[1, 0]`(오른쪽 방향)과 여러 벡터의 유사도를 비교해 봅니다. 방향이 멀어질수록 값이 1 → 0 → 음수로 작아집니다.

In [ ]:
base = np.array([1, 0])              # 기준: 오른쪽

same   = np.array([2, 0])            # 같은 방향 (길이만 2배)
diag   = np.array([1, 1])            # 45도 비스듬
ortho  = np.array([0, 1])            # 수직 (위쪽)
oppo   = np.array([-1, 0])           # 반대 방향

print('같은 방향:', round(cosine_similarity(base, same),  3))   # 1.0
print('45도    :', round(cosine_similarity(base, diag),  3))   # 0.707
print('수직    :', round(cosine_similarity(base, ortho), 3))   # 0.0
print('반대    :', round(cosine_similarity(base, oppo),  3))   # -1.0

> **핵심**: 코사인 유사도는 길이가 아니라 **방향**을 봅니다. 그래서 길이가 2배인 `[2, 0]` 도 `[1, 0]` 과 유사도가 1 입니다. 4·5차시에서 문장이나 이미지를 벡터로 바꾼 뒤, 이 값으로 "닮은 정도"를 잽니다.

> ## ✍️ 연습문제 4 · 함께 입력해 봐요

위에서 만든 `cosine_similarity` 함수를 사용합니다.
- 두 사용자의 영화 평점 벡터 `user1 = np.array([5, 3, 0, 1])`, `user2 = np.array([4, 3, 0, 1])` 를 만드세요.
- 두 사람의 취향이 얼마나 비슷한지 코사인 유사도를 구해 출력하세요. (1에 가까울수록 취향이 비슷합니다.)

In [ ]:
# ✍️ 여기에 직접 작성하세요 (위의 cosine_similarity 함수를 사용하세요)


## 6. 행렬 — 숫자를 표로 담다
**행렬(matrix)** 은 숫자를 **행(가로 줄)** 과 **열(세로 줄)** 의 격자로 정리한 표입니다. 리스트 안에 리스트를 넣어 만듭니다.

크기는 `.shape` 로 `(행 개수, 열 개수)` 형태로 확인합니다.

In [ ]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])   # 2행 3열 행렬
print(M)
# [[1 2 3]
#  [4 5 6]]
print('shape:', M.shape)   # shape: (2, 3)   ← (행 2, 열 3)
print('1행 2열 값:', M[1, 2])   # 1행 2열 값: 6   ← 행·열 모두 0번부터

### 6-1) 전치 — 행과 열 뒤집기
`.T` 를 붙이면 행과 열이 서로 바뀝니다. `(2, 3)` 행렬은 `(3, 2)` 가 됩니다.

In [ ]:
print('원래 행렬 shape:', M.shape)     # 원래 행렬 shape: (2, 3)
print('전치 행렬:')
print(M.T)
# [[1 4]
#  [2 5]
#  [3 6]]
print('전치 후 shape:', M.T.shape)    # 전치 후 shape: (3, 2)

### 6-2) 행렬곱 — `@` 연산자
행렬끼리 곱할 때도 `@` 를 씁니다. `(2, 3)` 행렬과 `(3, 2)` 행렬을 곱하면 `(2, 2)` 가 됩니다. (앞 행렬의 **열 개수** 와 뒤 행렬의 **행 개수** 가 같아야 곱할 수 있습니다.)

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])   # (2, 3)
B = np.array([[1, 0],
              [0, 1],
              [1, 1]])      # (3, 2)

C = A @ B                   # (2, 3) @ (3, 2) = (2, 2)
print(C)
# [[ 4  5]
#  [10 11]]
print('결과 shape:', C.shape)   # 결과 shape: (2, 2)

> ## ✍️ 연습문제 5 · 함께 입력해 봐요

- 행렬 `P = np.array([[2, 0], [1, 3]])` 를 만드세요.
- `P` 의 shape, 전치 행렬(`P.T`), 그리고 `P @ P.T` 를 각각 출력하세요.

In [ ]:
# ✍️ 여기에 직접 작성하세요


## 7. 이미지 = 숫자 행렬
흑백 이미지는 픽셀(작은 점)마다 **밝기 값 하나** 로 이루어진 2D 행렬입니다. 보통 `0`(검정) ~ `255`(흰색) 범위의 숫자를 씁니다.

아래는 5×5 픽셀에 그린 작은 **하트** 모양입니다. `0` 은 검정, `255` 는 흰색입니다. 숫자 격자만 봐도 모양이 보입니다.

In [ ]:
heart = np.array([
    [  0, 255,   0, 255,   0],
    [255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255],
    [  0, 255, 255, 255,   0],
    [  0,   0, 255,   0,   0],
])
print('이미지 shape:', heart.shape)   # 이미지 shape: (5, 5)
print(heart)

### 7-1) 그림으로 확인 — matplotlib
`matplotlib` 으로 숫자 행렬을 실제 이미지처럼 그려 봅니다. `imshow` 에 `cmap='gray'` 를 주면 흑백으로 보여 줍니다. (Colab에서 실행하면 그림이 셀 아래 나타납니다.)

In [ ]:
import matplotlib.pyplot as plt

plt.imshow(heart, cmap='gray')   # 행렬을 흑백 이미지로
plt.title('5x5 heart')
plt.axis('off')
plt.show()

### 7-2) 행렬 연산 = 이미지 편집
이미지가 숫자 행렬이므로, 숫자를 바꾸면 이미지가 바뀝니다. 예를 들어 `255 - 이미지` 를 하면 검정↔흰색이 뒤집혀 **색 반전** 이 됩니다.

In [ ]:
inverted = 255 - heart   # 모든 픽셀을 반전 (검정↔흰색)
print(inverted)

plt.imshow(inverted, cmap='gray')
plt.title('inverted')
plt.axis('off')
plt.show()

## 8. (선택) 임베딩으로 문장 유사도 재기
> 이 절은 **시간 여유가 있을 때만** 실행하세요. 라이브러리 설치에 1~2분이 걸리고, 4·5차시에서 자세히 다룹니다.

지금까지는 우리가 직접 숫자 벡터를 적었습니다. 실제 AI에서는 **문장**이나 **단어**를 컴퓨터가 자동으로 벡터(임베딩)로 바꿔 줍니다. 뜻이 비슷한 문장은 벡터도 비슷해져서, **코사인 유사도** 가 1에 가까워집니다. (5절에서 직접 만든 그 계산과 똑같습니다.)

아래 셀은 문장을 벡터로 바꿔 주는 `sentence-transformers` 를 설치합니다. **셀 맨 앞의 느낌표(`!`)** 는 설치 명령이라는 표시입니다.

In [ ]:
# (선택) 문장 임베딩 라이브러리 설치 — 실행에 1~2분 걸립니다.
# 시간 여유가 있을 때만 이 셀을 실행하세요.
!pip install -q sentence-transformers

설치가 끝나면 아래 셀로 모델을 불러오고, 두 문장을 벡터로 바꿔 유사도를 계산합니다. 앞에서 만든 식과 달리, 여기서는 라이브러리가 제공하는 코사인 유사도 함수를 그대로 씁니다.

In [ ]:
# (선택) 위 설치 셀을 실행한 뒤에만 동작합니다.
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')   # 가벼운 문장 임베딩 모델

sentences = [
    '고양이가 소파 위에서 잠을 잔다.',
    '고양이 한 마리가 소파에서 자고 있다.',   # 위 문장과 뜻이 비슷
    '오늘 점심으로 김치찌개를 먹었다.',         # 전혀 다른 내용
]
emb = model.encode(sentences)   # 문장 3개를 각각 벡터로 변환
print('임베딩 shape:', emb.shape)   # (3, 384) ← 문장 3개, 각 384차원 벡터

In [ ]:
# (선택) 1번 문장을 기준으로 나머지와의 코사인 유사도
sim_similar = util.cos_sim(emb[0], emb[1]).item()   # 뜻이 비슷한 문장
sim_diff    = util.cos_sim(emb[0], emb[2]).item()   # 내용이 다른 문장

print(f'비슷한 문장과의 유사도: {sim_similar:.3f}')   # 0.8 안팎 (높음)
print(f'다른 문장과의 유사도  : {sim_diff:.3f}')      # 0.1 안팎 (낮음)

> 사람이 보기에 비슷한 문장은 유사도가 높고, 다른 문장은 낮게 나옵니다. 이렇게 **의미를 벡터로 바꿔 유사도로 비교** 하는 것이 검색·추천·RAG 챗봇의 핵심입니다. 5차시에서 이 임베딩으로 직접 챗봇을 만듭니다.

## 마무리
- **NumPy 배열**(`np.array`)은 같은 자리끼리 계산해 줘서 벡터·행렬 연산에 알맞습니다.
- **내적**(`@`)은 대응 원소를 곱해 더한 하나의 수이고, **노름**(`np.linalg.norm`)은 벡터의 길이입니다.
- **코사인 유사도** 는 내적을 길이로 나눠 **방향이 비슷한 정도** 를 잰 값으로, 임베딩 비교의 바탕이 됩니다.
- **행렬** 은 숫자의 표이며, **이미지도 픽셀 밝기의 행렬** 입니다. `.T`(전치)·`@`(행렬곱)로 다룹니다.

다음 노트북(4차시)에서는 이 벡터·행렬을 재료로 **머신러닝 모델을 직접 만들어** 봅니다.